title: Felicity Bui
description: Welcome to my data science portfolio
#show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: http://example.com/download.zip
  another_url: https://www.linkedin.com/in/felicitybui/
